server:
    port: 8761
spring:
    application:
      name: eureka-service
    security:
       basic:
          enabled: true
       user:
         name: caffac
         password: cheng1990

eureka:

    instance:
      hostname: 47.107.231.96
      prefer-ip-address: true
    server:
      #eviction-interval-timer-in-ms: 5000
      enable-self-preservation: false
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@47.100.210.186:8761/eureka/
