server:
  port: 9091
spring:
  application:
    name: user-service
eureka:
  client:
    security:
          basic:
            user: caffac
            password: cheng1990
    serviceUrl:
       defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@47.107.231.96:8761/eureka/,http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@47.100.210.186:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000