server:
  port: 8763
spring:
  application:
    name: eureka-client
eureka:
  client:
    security:
      basic:
        user: caffac
        password: cheng1990
    serviceUrl:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
